[workspace]

members = [
    "bin",
    "matching",
    "merge",
    "parsing",
    "model"
, "pretty-printing"]

[workspace.dependencies]
log = "0.4.20"
uuid = { version = "1.7.0", features = ["v4"] }
