[package]
name = "pretty-printing"
version = "0.1.0"
edition = "2024"

[lib]
name = "pretty_printing"
path = "src/lib.rs"

[dependencies]
tree-sitter = "0.25.8"

[dev-dependencies]
tree-sitter-java = "0.23.5"
